project:
  type: website
  output-dir: docs

website:
  title: "Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_analysis.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



