---
title: "About"
---

Educational Background:

I grew up in Washington DC and attended the School without Walls high shcool. I then went on to study math at Haverford College, where I also completed a minor in chemistry and a minor in spanish. Throughout college I tried to merge my interests in math and science, I did research in a computational chemistry lab at Haverford and did a mathematical biology summer research experience. All of these experiences led me to want to see new ways that science and math could be used together to explain the world. I continued this path working at a biotech startup after graduating from college. During that job I realized that biostatistics was the field where I could apply math to explain scientific phenomena and I applied for my PHD. I am very excited to be starting my PHD here at Johns Hopkins and am excited to learn even more ways to apply statistics and math to science. 

Hobbies:

I was a setter on the volleyball team at Haverford College so I am now trying to find places to play in Baltimore. I also love to play board games and card games, my favorite at the moment is Bohnanza. Finally, I like to go backpacking and camping and worked at a summer camp for a few summers leading backpacking trips for young people. 
